### ISSUE TITLE
Sustain+release+pianoswitch issue

### ISSUE THREAD

**Issue by mulshine** [Princeton-CDH/bitKlavier#84]
1. Press sustain
2. Play and hold some notes (order of 1/2 can be reversed)
3. Change piano
4. Release notes
5. Release sustain (if order of 4/5 are reversed, it works as expected)

^ Should result in nostalgic notes on previous piano, but does not.

**Comment by mulshine** [comment]
I think this is solved.

**Comment by dantrueman** [comment]
did you push a fix in the last few minutes? it's still not working right with the current pull of dev

**Comment by dantrueman** [comment]
fixed
